const tools = {
  porcentaje:{title:'Calculadora de porcentaje',icon:'%',cat:'Cálculos',desc:'Calcula un porcentaje de cualquier cantidad.',fields:[['cantidad','Cantidad','number'],['porcentaje','Porcentaje','number']],run:v=>fmt(num(v.cantidad)*num(v.porcentaje)/100)},
  regla3:{title:'Regla de tres',icon:'↔',cat:'Cálculos',desc:'Resuelve proporciones de forma inmediata.',fields:[['a','Si A vale','number'],['b','y B vale','number'],['c','entonces C vale','number']],run:v=>{let a=num(v.a);if(a===0)throw Error('El primer valor no puede ser cero.');return fmt(num(v.b)*num(v.c)/a)}},
  descuento:{title:'Calculadora de descuento',icon:'↓',cat:'Cálculos',desc:'Averigua el precio final con descuento.',fields:[['precio','Precio original','number'],['descuento','Descuento (%)','number']],run:v=>`Precio final: ${fmt(num(v.precio)*(1-num(v.descuento)/100))}`},
  iva:{title:'Calculadora de IVA',icon:'$',cat:'Cálculos',desc:'Calcula el IVA y el total a pagar.',fields:[['base','Precio sin IVA','number'],['tasa','IVA (%)','number']],run:v=>{let i=num(v.base)*num(v.tasa)/100;return `IVA: ${fmt(i)}\nTotal: ${fmt(num(v.base)+i)}`}},
  edad:{title:'Calculadora de edad',icon:'◷',cat:'Fechas',desc:'Conoce tu edad exacta en años.',fields:[['nacimiento','Fecha de nacimiento','date']],run:v=>{let d=new Date(v.nacimiento+'T00:00:00'),n=new Date();if(isNaN(d))throw Error('Elige una fecha válida.');let e=n.getFullYear()-d.getFullYear(),m=n.getMonth()-d.getMonth();if(m<0||(m===0&&n.getDate()<d.getDate()))e--;return `Tienes ${e} años.`}},
  dias:{title:'Días entre fechas',icon:'↗',cat:'Fechas',desc:'Cuenta los días que hay entre dos fechas.',fields:[['inicio','Fecha inicial','date'],['fin','Fecha final','date']],run:v=>{let a=new Date(v.inicio+'T00:00:00'),b=new Date(v.fin+'T00:00:00');if(isNaN(a)||isNaN(b))throw Error('Completa las dos fechas.');return `${Math.abs(Math.round((b-a)/86400000))} días.`}},
  palabras:{title:'Contador de palabras',icon:'Aa',cat:'Texto',desc:'Cuenta palabras, caracteres y líneas.',text:true,run:v=>{let t=v.texto.trim();return `Palabras: ${t?t.split(/\s+/).length:0}\nCaracteres: ${v.texto.length}\nLíneas: ${v.texto? v.texto.split(/\r?\n/).length:0}`}},
  mayusculas:{title:'Conversor de texto',icon:'⇧',cat:'Texto',desc:'Pasa texto a mayúsculas, minúsculas o título.',text:true,select:true,run:v=>v.modo==='mayusculas'?v.texto.toUpperCase():v.modo==='minusculas'?v.texto.toLowerCase():v.texto.toLowerCase().replace(/(^|\s)\S/g,x=>x.toUpperCase())},
  espacios:{title:'Limpiar espacios',icon:'≋',cat:'Texto',desc:'Elimina espacios y líneas sobrantes.',text:true,run:v=>v.texto.replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').trim()},
  contrasena:{title:'Generador de contraseñas',icon:'✦',cat:'Utilidades',desc:'Crea contraseñas aleatorias y seguras.',fields:[['longitud','Longitud (8–64)','number']],run:v=>{let n=Math.max(8,Math.min(64,Math.round(num(v.longitud)||16))),c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%*?';let r=crypto.getRandomValues(new Uint32Array(n));return Array.from(r,x=>c[x%c.length]).join('')}},
  uuid:{title:'Generador de UUID',icon:'◈',cat:'Utilidades',desc:'Crea identificadores únicos al instante.',run:()=>crypto.randomUUID()},
  json:{title:'Formateador JSON',icon:'{ }',cat:'Utilidades',desc:'Valida y da formato legible a tu JSON.',text:true,run:v=>JSON.stringify(JSON.parse(v.texto),null,2)}
};
const num=x=>{let n=Number(x);if(!Number.isFinite(n))throw Error('Introduce números válidos.');return n};const fmt=n=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(n);
const base='../';
function card(key,t){return `<a class="tool-card" data-search="${t.title} ${t.cat} ${t.desc}" href="herramientas/${key}.html"><div class="tool-icon">${t.icon}</div><h3>${t.title}</h3><p>${t.desc}</p><small>${t.cat} →</small></a>`}
function initHome(){let grid=document.querySelector('#tool-grid');if(!grid)return;grid.innerHTML=Object.entries(tools).map(([k,t])=>card(k,t)).join('');document.querySelector('#tool-search').addEventListener('input',e=>{let q=e.target.value.toLowerCase();grid.querySelectorAll('.tool-card').forEach(c=>c.classList.toggle('hidden',!c.dataset.search.toLowerCase().includes(q)))})}
function initTool(){let root=document.querySelector('[data-tool]');if(!root)return;let key=root.dataset.tool,t=tools[key];document.title=`${t.title} | Caja Útil`;document.querySelector('#tool-title').textContent=t.title;document.querySelector('#tool-desc').textContent=t.desc;let form=document.querySelector('#tool-form');let html='';if(t.text)html+='<label class="field full">Texto<textarea name="texto" placeholder="Escribe o pega aquí tu texto"></textarea></label>';if(t.select)html+='<label class="field full">Transformación<select name="modo"><option value="mayusculas">MAYÚSCULAS</option><option value="minusculas">minúsculas</option><option value="titulo">Tipo título</option></select></label>';(t.fields||[]).forEach(([n,l,type])=>html+=`<label class="field">${l}<input name="${n}" type="${type}" ${type==='number'?'step="any"':''}></label>`);html+='<div class="actions full"><button class="button" type="submit">Calcular</button><button class="button secondary" type="reset">Limpiar</button></div>';form.innerHTML=html;let out=document.querySelector('#result');form.addEventListener('submit',e=>{e.preventDefault();try{let v=Object.fromEntries(new FormData(form));out.textContent=t.run(v);out.classList.remove('error')}catch(err){out.textContent=err.message||'Revisa los datos e inténtalo otra vez.';out.classList.add('error')}});form.addEventListener('reset',()=>{out.textContent='El resultado aparecerá aquí.';out.classList.remove('error')});let related=Object.entries(tools).filter(([k,x])=>k!==key&&x.cat===t.cat).slice(0,4);document.querySelector('#related').innerHTML=related.map(([k,x])=>`<li><a href="${k}.html">${x.title}</a></li>`).join('')||'<li><a href="../index.html">Ver todas las herramientas</a></li>'}
initHome();initTool();
